---
# tasks file for craigmj.mariadb.10
- name: Install curl, python-mysqldb, python-pycurl, software-properties-common
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - software-properties-common
    - python-pycurl
    - python-mysqldb

- name: Add MariaDB apt key
  sudo: yes
  command: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db"

- name: Add MariaDB Repo
  sudo: yes
  apt_repository: "repo='deb http://ftp.wa.co.za/pub/mariadb/repo/10.0/ubuntu {{ansible_distribution_release}} main' state=present update_cache=yes"

- name: Install MariaDB 10 Server and Client
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ ansible_hostname }} password={{ mysql_root_db_pass }}
  when: ansible_hostname != 'localhost' 

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
