---
# tasks file for craigmj.mariadb.10
- name: Install curl, python-pycurl, software-properties-common
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - software-properties-common
    - python-pycurl

- name: Add MariaDB apt key
  sudo: yes
  command: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db"

- name: Add MariaDB Repo
  sudo: yes
  apt_repository: "repo='deb http://ftp.wa.co.za/pub/mariadb/repo/10.0/ubuntu saucy main' state=present update_cache=yes"

- name: Install MariaDB 10 Server and Client
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
